theme: minima
baseurl: "/DE"
title: "Сетевой анализ персонажей Disco Elysium"
description: "Финальный проект курса «Цифровые технологии в профессиональной деятельности» · ФГН НИУ ВШЭ · 2026"
show_excerpts: false
